# Generated by Django 2.1.7 on 2019-03-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_intern',
            new_name='is_owner',
        ),
    ]
