# Generated by Django 2.1.7 on 2019-03-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0004_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='author',
            new_name='owner',
        ),
    ]
