# Generated by Django 2.1.7 on 2019-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0005_auto_20190321_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
