# Generated by Django 2.1.7 on 2019-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0006_auto_20190321_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_pics'),
        ),
    ]
