# Generated by Django 2.1.7 on 2019-03-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0007_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='rest_default.jpg', upload_to='restaurant_pics'),
        ),
    ]
