# Generated by Django 2.1.7 on 2019-03-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0008_auto_20190321_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
