# Generated by Django 2.1.7 on 2019-04-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0012_auto_20190322_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('cuisine', models.CharField(max_length=50)),
                ('image', models.ImageField(default='rest_default.jpg', upload_to='restaurant_pics')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launch.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='location',
        ),
    ]
