# Generated by Django 2.1.7 on 2019-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0013_auto_20190403_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
