# Generated by Django 2.1.7 on 2019-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0015_auto_20190403_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='data_ordered',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
