# Generated by Django 2.1.7 on 2019-04-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0016_auto_20190403_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
    ]
