# Generated by Django 2.1.7 on 2019-04-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0017_auto_20190403_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='cart',
        ),
    ]
