# Generated by Django 2.1.7 on 2019-04-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0018_remove_customerprofile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='cart',
            field=models.ManyToManyField(blank=True, to='launch.Item'),
        ),
    ]
