# Generated by Django 2.1.7 on 2019-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0024_auto_20190408_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cuisine',
        ),
    ]
